name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "main"
  pull_request:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  Linter:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - run: npx awesome-lint